[build]
  command = "npm install"  # Instala as dependências
  publish = "."  # Publica todos os arquivos no diretório atual

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/dolar-ptax/*"
  to = "/index.html"
  status = 200