[build]
  command = "npm run build"
  publish = "dist"

[dev]
  command = "npm run start:dev"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/dolar-ptax/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 404