[build]
  command = "npm run build" # Comando para construir a aplicação
  publish = "dist" # Pasta onde os arquivos construídos são armazenados

[dev]
  command = "npm run start:dev" # Comando para iniciar em ambiente de desenvolvimento

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200